### ISSUE TITLE
Grade 1 (partly contracted)

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-nota#15]
@stesk I assume this is still an important requirement? To be prioritized?

**Comment by stesk** [comment]
@bertfrees Yes, I realised only yesterday that I forgot to mention this after AT. A major mistake on my part, sorry about that. This requirement has the highest priority. I will take a look at the tables next week and see if I can make something happen. Making the table itself ought to be fairly simple, but of course it has to be integrated with the option.

**Comment by bertfrees** [comment]
Should we get Bue in the loop? He has mentioned to me that he has also been thinking about such a table, and maybe he has done something already?

**Comment by bertfrees** [comment]
Status update: we received a table from Bue and Steffen is currently testing it.

**Comment by bertfrees** [comment]
Steffen has tested. The table is OK.
