### ISSUE TITLE
Automatic numbering on type "ol" lists

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-nota#9]
This should normally only require changes to the CSS file, but in order to be sure I need more details.

**Comment by stesk** [comment]
I tested the XHTML and DTBook scripts using the input files found here: [https://github.com/stesk/danishbraille/tree/master/tests/lists](https://github.com/stesk/danishbraille/tree/master/tests/lists), with this CSS: [https://github.com/stesk/danishbraille/blob/master/css/nota_braille.css](https://github.com/stesk/danishbraille/blob/master/css/nota_braille.css), but nothing happened.

**Comment by bertfrees** [comment]
Try with `li { display:list-item; }`

**Comment by bertfrees** [comment]
@stesk What is the status here again? I think you said it worked. Is there something I need to incorporate in the default CSS or not just yet?

**Comment by stesk** [comment]
@bertfrees The status is that the numbering definitely works. Thanks for pointing out `display: list-item`! I haven't tested advanced styling of list items with `::marker` yet, though. I imagine you could use it to have the same indentation on all list items regardless of marker width? I like that for print, of course, but I imagine it gets pretty cramped with the limited horizontal space on a braille page. Either way it's not a requirement for us. So all in all I would consider this issue closed.

**Comment by bertfrees** [comment]
Yes that's the idea of `::marker` but that hasn't been implemented. OK I'll close. Thanks.
